# Generated by Django 4.0.4 on 2022-11-13 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='liked_movies',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
