# Generated by Django 4.0.4 on 2022-11-13 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_liked_movies'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='disliked_movies',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
