# Generated by Django 4.0.4 on 2022-11-21 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_timestamp_liked_movies'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='timestamp_disliked_movies',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
